language: python

python:
  - "3.6"

env:
  global:
    - EPANET_HOME=`pwd`
    - BUILD_HOME=buildproducts
    - TEST_HOME=nrtestsuite

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost-test-dev
  - sudo apt-get install libpcre3-dev bison
  - wget -O swig-rel-3.0.12.tar.gz https://github.com/swig/swig/archive/rel-3.0.12.tar.gz && tar -xf swig-rel-3.0.12.tar.gz && cd swig-rel-3.0.12 && ./autogen.sh && ./configure && make -j 4 && sudo make install && cd ..
  - pip install pipenv

#install:

before_script:
  - mkdir -p $BUILD_HOME
  - cd $BUILD_HOME
  - cmake .. -DBUILD_TESTS=1

script:
  - cmake --build .
  # run unit tests
  - cd tests/unit
  - ctest
  # run regression tests
  - cd $EPANET_HOME/tests/regression
  - pipenv install
  - pipenv run python3 run_test.py $TEST_HOME 2012gcc 1.0.1 $TRAVIS_COMMIT $EPANET_HOME/$BUILD_HOME/bin/runepanet
