sudo: required
language: python

python:
  - "3.6"

services:
  - docker

env:
  global:
    - EPANET_HOME=`pwd`
    - BUILD_HOME=buildproducts
    - TEST_HOME=nrtestsuite

before_install:
  - sudo apt-get -qq update

install:
  -

before_script:
  - cd ..

script:
  - docker run -v $BUILD_HOME:/epanet openwateranalytics/epanet_builder:latest bash -c "mkdir buildproducts && cd buildproducts && cmake .. -DBUILD_TESTS=1 && make && cd ../tests/regression && pipenv install && pipenv run python3 run_test.py $TEST_HOME 2012gcc 1.0.1 $TRAVIS_COMMIT /epanet/$BUILD_HOME/bin/runepanet"
